name: 2277A Neptune Way
favicon: null
layout_spectrum: 0.50386
typography_spectrum: 0.8368200927507132
title: '2277A Neptune Way, Comox'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#ffffff'
    - '#a8a9a3'
    - '#878782'
    - '#372d2c'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
