name: 2277A Neptune Way
favicon: null
layout_spectrum: 0.32445
typography_spectrum: 0.48844
title: '2277A Neptune Way, Comox'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121212'
    - '#803f20'
    - '#8b9168'
    - '#d1b492'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
