name: 2277A Neptune Way
favicon: null
layout_spectrum: 0.888729443307966
typography_spectrum: 0.8368200927507132
title: '2277A Neptune Way, Comox'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8792341807857156
  lightness: 0.6873368576634675
  saturation: 0.8406213612761348
  rhythmicContrast: 0.3276988575235009
purpose: []
